### ISSUE TITLE
Tibia Client Login hangs with OTClient but not with vanilla client + TibiaLoader/IPChanger

### ISSUE THREAD

**Issue by SeeingBlue** [jlnunez89/fibula-mmo#45] opened 2020-01-12 09:21 UTC
After following all the instructions, I am able to compile and run the standalone server.

My tibia client I used with Tibia Load will connect and load my character list, but once I pick my character and try to connect, the client will crash.

I've also tried the custom OTLand client and it does the same thing. After selecting my character it never connects, just sits there doing nothing.

No errors show up in the server console.

**Comment by jlnunez89** [comment] 2020-01-12 10:02
Hi! which client versions are you using? 
I've been currently developing with Cip's client version 7.7 and can log in, but so far you're the first other datapoint I;ve gotten, so I'd appreciate more info on your setup. Looking forward!

**Comment by jlnunez89** [comment] 2020-01-12 11:54
So I did some more digging. It seems like OTClient is also hanging. Seems to have something to do with how the encryption keys are used and how they differ from CIP keys/OTserv keys. 

I've also confirmed 7.7 and 7.72 are working with both Tibia Loader and OTLand's IPChanger. 

I don't know where to get other clients but I'll look into why OTClient doesn't like the keys.

I merged #47 so that it's logged in the console when the reason for hanging is bad keys.

**Comment by jlnunez89** [comment] 2020-01-12 11:56
also, (for anyone else reading) if you're using 7.72 you'll need to change the numeric version in **appsettings.json**

**Comment by SeeingBlue** [comment] 2020-01-12 15:19
This URL has a lot of client downloads: https://ots-list.org/download

The original 770 tibia client with Tibia Loader or Otland IP Changer, it will let me login to character selection but will crash the client when trying to log into the character.

So I change the appsettings.json to read 772 and try the same thing with OTland Loader(because Tibia loader doesn't support 772) again using the original Tibia clients. This time the client does not crash but I get an error after character selection that says Cannot connect to the game server.

So far I am able to run the server just fine and reach character selection but cannot go any further. Maybe I am missing something, but it's not producing an error?

**Comment by jlnunez89** [comment] 2020-01-12 19:34
Thanks, I'll with the client you sent in a bit, need to step away for a sec.
I'll also try to do a clean setup (following my own instructions) and see how it goes.

**Comment by SeeingBlue** [comment] 2020-01-12 20:52
This may be helpful, it is from Tibia client 7.70
![image](https://user-images.githubusercontent.com/7357172/72225445-95ccb500-3553-11ea-8778-51d390618bcd.png)

**Comment by SeeingBlue** [comment] 2020-01-12 20:55
This is Tibia client 7.72. Occurs when trying to login/load character list.
![image](https://user-images.githubusercontent.com/7357172/72225490-04117780-3554-11ea-8e8d-8aa269950010.png)

**Comment by SeeingBlue** [comment] 2020-01-12 21:04
I finally got 7.70 to work and I don't really understand why.

**Comment by jlnunez89** [comment] 2020-01-12 21:35
Yup, I can repro downloading the 7.72 client from the list you sent, and using OTLand's IP changer.
So far, it seems that keys are different between versions 7.70 and 7.72, and OTClient may also do it differently? (i.e these guys made a change to make OTClient work back then: https://github.com/CoreOpenMMO/CoreOpenMMO/commit/ca765785c2dc2f7d60237f89e680bc2110e4c9de?diff=split) 

I'm looking at what the current state is to see exactly what combination of client/keys break, and also to incorporate the changes made by them to make this work once and for all. Thanks for all the supplementary info!

**Comment by jlnunez89** [comment] 2020-01-12 21:47
btw, I just had Amirolso create a channel on their discord server, we can take it there for more instant communication: https://discord.gg/GpMJt9

**Comment by jlnunez89** [comment] 2020-01-13 00:12
K finally figured it out. Take a look at #51 if interested.
Turns out in 7.7 the client version and OS are encrypted in the login message packet.
After 7.72 the version is left outside, un-encrypted.

Thanks for the patience!

**Closed by jlnunez89** 2020-01-13 00:12 UTC
